name: Infrastructure Check

on:
  push:
  pull_request:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup CI environment
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          install_args: "--locked"

      - name: Install dependencies
        run: task setup

      - name: Lint
        run: task lint:check

      - name: Docs
        run: task docs:check